In [1]:
import numpy as np
a = np.array([1,2,3])
a

array([1, 2, 3])

In [2]:
a = np.array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

In [3]:
x = np.zeros([2,3])
x

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [4]:
x = np.ones([2,3])
x

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [5]:
x = np.empty([3,3])
x

array([[  0.00000000e+000,   6.62047965e-321,   2.47032823e-323],
       [  1.20117428e-311,   0.00000000e+000,   9.71407170e-319],
       [  1.20117522e-311,   0.00000000e+000,   1.60219034e-306]])

In [6]:
x = np.full([2,3],7)
x

array([[7, 7, 7],
       [7, 7, 7]])

In [7]:
x = np.eye(7)
x

array([[ 1.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  1.]])

In [8]:
a = np.arange(0,10,2)
a

array([0, 2, 4, 6, 8])

In [9]:
a = np.arange(0,9).reshape(3,3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [10]:
np.linspace(0,2,12)

array([ 0.        ,  0.18181818,  0.36363636,  0.54545455,  0.72727273,
        0.90909091,  1.09090909,  1.27272727,  1.45454545,  1.63636364,
        1.81818182,  2.        ])

In [11]:
print(np.arange(0,9).reshape(3,3))

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [12]:
np.array([[1,2],[3,4]],dtype=complex)

array([[ 1.+0.j,  2.+0.j],
       [ 3.+0.j,  4.+0.j]])

In [13]:
x=np.arange(0,12).reshape(2,2,3)
x

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [14]:
x.size


12

In [15]:
x.itemsize

4

In [17]:
x=np.array([1,2])
y=np.array([3,4])
x**y

array([ 1, 16], dtype=int32)