<h1><center>CSE391 programming for data science</center></h1>

<h1><center>Lecture 12</center></h1>
<h1><center>Feb 28th ,2018 </center></h1>



# Information is the oil of the 21st century, and analytics is the combustion engine.
- ~ Peter Sondergaard, SVP, Gartner Research – 

# Jupyter notebook Tips of the day

# Colors: 

-Use this code: <font color=red>Text</font> Not all markdown code works within a font tag, so review your colored text carefully!

# Indenting: 
-Use a greater than sign (>) and then a space, then type the text. Everything is indented until the next carriage return.
> here


#  Dealing with missing values

# Two type of missing data
- missing completly at random
- mising not at random

# How to deal with missing data
- drop out 
- imputation 
     - expert gussing
     - averaging 
     - regression
     - Expectation maximization


# 1.1 Drop the missing values.

In [ ]:
passengers.dropna(axis=0, how='any', thresh=None, subset=None, inplace=False)



- This will drop any rows with missing values. Clearly this isn't a good idea
- What instead if we wanted to remove any columns with missing values? How?

In [ ]:
passengers.dropna(axis = 1).head(5)

In [ ]:
# Keep only the rows with at least 11 non-na values:
passengers.dropna(thresh = 11)

# 1.2 imputation ( a way to replace the missing values) 
- Filling the missing values
    -  mean
    - your suggestion?

In [ ]:
 passengers["Age"].fillna(value=passengers["Age"].mean()).head()

# The apply function in Pandas
-This is one of the most powerful tools available in Pandas. Apply, allows you to either use Python's built-in functions or to create your own custom function and then run it across a set of your data.

## let's define a function to map each embarked city to a letter

In [ ]:
def get_full_city_name(cityCode):
    if (cityCode == "S"):
        return "Southampton"
    elif (cityCode == "C"):
        return "Cherbourg"
    elif (cityCode == "Q"):
        return "Queenstown"

In [ ]:
passengers["Embarked"].apply(get_full_city_name).head(10)

# Using Lambda function
Lambda expressions allow you to create functions on the fly. This means you can create a function when you need it and then apply that to the relevant data set.

In [ ]:
# Updating the fares for all the passengers
passengers["Fare"].apply(lambda fare: 106 * fare).head(5)

# Boolian Indexing in Pandas
- selecting across multiple columns with python pandas


In [ ]:
# creat a data frame

d = pd.DataFrame({'x':[1, 2, 3, 4, 5], 'y':[4, 5, 6, 7, 8]})
d

In [ ]:
d[(d['x']>2) & (d['y']>7)]

- List comprehensions and map method of DataFrames can also be used to produce more complex column selection criteria:

In [7]:
import numpy as np
import pandas as pd
df2 = pd.DataFrame({'a' : ['one', 'one', 'two', 'three', 'two', 'one', 'six'], 'b' : ['x', 'y', 'y', 'x', 'y', 'x', 'x'],  'c' : np.random.randn(7)})
        
df2

a  b         c
0    one  x -0.438498
1    one  y  1.125559
2    two  y  0.879268
3  three  x -0.184626
4    two  y  0.913174
5    one  x  0.336748
6    six  x  1.778274

In [8]:

criterion = df2['a'].map(lambda x: x.startswith('t'))
print(criterion)

print(df2[criterion])

0    False
1    False
2     True
3     True
4     True
5    False
6    False
Name: a, dtype: bool
       a  b         c
2    two  y  0.879268
3  three  x -0.184626
4    two  y  0.913174


In [3]:
# More on array indexing and slicing 
# based on an arti\cle from Ayushi Asthana at geeksforgeeks

import numpy as np 
a = np.array([[1,2,3],[3,4,5],[4,5,6]]) 
print(a ) 

# slice items starting from index
print('Now we will slice the array from the index a[1:]' )
print(a[1:])

# Python program for basic slicing.
import numpy as np
 
# Arrange elements from 0 to 19
a = np.arange(20)
print("\n Array is:\n ",a)
 
# a[start:stop:step]
print("\n a[-8:17:1]  = ",a[-8:17:1]) 
 
# The : operator means all elements till the end.
print("\n a[10:]  = ",a[10:])

# Advanced indexing

#Purely integer indexing
# Python program showing advanced indexing
import numpy as np
 
a = np.array([[1 ,2 ],[3 ,4 ],[5 ,6 ]])
print(a[[0 ,1 ,2 ],[0 ,0 ,1]])

#Boolean Indexing 
# You may wish to select numbers greater than 50
import numpy as np
 
a = np.array([10, 40, 80, 50, 100])
print(a[a>50])

# You may wish to square the multiples of 40 
import numpy as np
 
a = np.array([10, 40, 80, 50, 100])
print(a[a%40==0]**2)

[[1 2 3]
 [3 4 5]
 [4 5 6]]
Now we will slice the array from the index a[1:]
[[3 4 5]
 [4 5 6]]

 Array is:
  [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]

 a[-8:17:1]  =  [12 13 14 15 16]

 a[10:]  =  [10 11 12 13 14 15 16 17 18 19]
[1 3 6]
[ 80 100]
[1600 6400]
