In [1]:
import numpy as np
x=np.matrix([1,2,3]).T
x

matrix([[1],
        [2],
        [3]])

In [2]:
y=np.matrix([4,5,6]).T
y

matrix([[4],
        [5],
        [6]])

In [3]:
S=np.matrix([[2,1,4],[5,-1,3],[1,7,2]])
S

matrix([[ 2,  1,  4],
        [ 5, -1,  3],
        [ 1,  7,  2]])

In [4]:
A=np.matrix([[0.4,0.1,0.14],[12.4,-0.01,0.3],[1.6,7.5,0.2]])
A

matrix([[  4.00000000e-01,   1.00000000e-01,   1.40000000e-01],
        [  1.24000000e+01,  -1.00000000e-02,   3.00000000e-01],
        [  1.60000000e+00,   7.50000000e+00,   2.00000000e-01]])

In [8]:
def cal(x,y,s,a):
    p1 = y.T.dot(np.outer(x,y))
    p2 = p1.dot(a)
    p3 = p2.dot(np.diag(np.diag(np.linalg.inv(s))))
    p4 = p3.dot(y)
    p5 = (1/np.linalg.det(A)**2)*p4
    return p5

In [9]:
cal(x,y,S,A)

matrix([[-17.00165995]])

In [10]:
%%writefile /Users/jzckk/quiz2_7.py
import numpy as np
x=np.matrix([1,2,3]).T
y=np.matrix([4,5,6]).T
S=np.matrix([[2,1,4],[5,-1,3],[1,7,2]])
A=np.matrix([[0.4,0.1,0.14],[12.4,-0.01,0.3],[1.6,7.5,0.2]])

def cal(x,y,s,a):
    p1 = y.T.dot(np.outer(x,y))
    p2 = p1.dot(a)
    p3 = p2.dot(np.diag(np.diag(np.linalg.inv(s))))
    p4 = p3.dot(y)
    p5 = (1/np.linalg.det(A)**2)*p4
    return p5

Overwriting /Users/jzckk/quiz2_7.py
